### ISSUE TITLE
[230701] (토) 오늘의 공부

### ISSUE THREAD

**Issue by hoonii2** [let-s-study-with/TWL#102]
댓글로 자신이 어떤 공부 할지 체크박스를 만들고 얼만큼 했는지 체크해주세요.

**Comment by lala9663** [comment]
- [ ] 알고리즘 스터디 문제
- [ ] 정처기 공부시작하기
- [ ] 섹션 5,6 완강
- [ ] 프로그래머스 d-14

**Comment by hoonii2** [comment]
- [ ] 알고리즘 최대한 많이 손코딩 , 정답 확인
- [ ] 유형 별로 특징 정리

**Comment by JeYeongR** [comment]
- [ ] "모던 자바 인 액션" 책 1장 보기
- [ ] "모던 자바 인 액션" 책 2장 보기
- [ ] 프로그래머스 레벨 2 문제 풀기
