### ISSUE TITLE
[230714] (금) 오늘의 공부

### ISSUE THREAD

**Issue by hoonii2** [let-s-study-with/TWL#133]
댓글로 자신이 어떤 공부 할지 체크박스를 만들고 얼만큼 했는지 체크해주세요.

**Comment by smallsnail-study** [comment]
- [ ]  정처기 HW 구축관리 문제&내용정리
- [ ]  정처기 DB 구축관리 문제&내용정리
- [ ]  10814 나이순 정렬 코드 복습
- [ ]  인프런 스프링 웹 개발 기초 수강&내용정리
- [ ]  자바의 정석 ch11-2~11-24 수강&내용정리
- [ ]  자바의 정석 ch11-1~11-24 예제풀이
- [ ]  웹브라우저 → 서버 1(EC2)  →  RDS(Database 1) 동시에 500명 요청 지속해서 문제점,해결방법 정리
- [ ]  collection 관련 과제 작성

**Comment by JeYeongR** [comment]
- [ ] 코테 스터디 문제 풀기
- [ ] "클린 코드" 책 1장 보기
- [ ] "Real MySQL" 책 1장 보기
- [ ] "Real MySQL" 책 2장 보기

**Comment by lala9663** [comment]
- [ ] 프로젝트 구조 어떻게 나누는게 좋을지 찾아보기
- [ ] 코데 스터디 문제 올리기
- [ ] 프로그래머스 d- 19 까지 풀기

**Comment by hoonii2** [comment]
- [ ] DDD - 아키텍처 , Aggregator
- [ ] 클린코드 - 함수 , 주석
- [ ] TDD - 기능 명세 / 설계 , JUnit 기초
- [ ] 코테 스터디 문제 풀기

**Comment by suji5262** [comment]
- [ ]  스프링
- [ ] 자바
