### ISSUE TITLE
[230717] (월) 오늘의 공부

### ISSUE THREAD

**Issue by hoonii2** [let-s-study-with/TWL#138]
댓글로 자신이 어떤 공부 할지 체크박스를 만들고 얼만큼 했는지 체크해주세요.

**Comment by lala9663** [comment]
- [ ] 코테: 2주차 제영이꺼, 우석이형꺼 풀기
- [ ] 프로그래머스 d-21
- [ ] 인프런 MVC1 듣기
- [ ] 클린 코드 1장
- [ ] 자료구조 set 정리
- [ ] 치과
- [ ] 운동

**Comment by suji5262** [comment]
- [ ] 자바
- [ ] 스프링
- [ ] 코테 공부

**Comment by hoonii2** [comment]
- [ ] DDD - Repository 조회 기능 (JPA)
- [ ] 클린 코드 - 형식 맞추기
- [ ] TDD - 테스트 코드의 구성
- [ ] 코테 스터디 문제 풀기

**Comment by JeYeongR** [comment]
- [ ] 코테 스터디 문제 풀기

**Comment by smallsnail-study** [comment]
- [ ]  200626 정보처리기사 기출문제 풀고 이론확인
- [ ]  200822 정보처리기사 기출문제 풀고 이론확인
- [ ]  200926 정보처리기사 기출문제 풀고 이론확인
- [ ]  spring 인강 라이브러리 살펴보기 수강&강의노트 작성
- [ ]  spring 인강 view 환경설정 수강&강의노트 작성
- [ ]  spring 인강 빌드하고 실행하기 수강&강의노트 작성
