### ISSUE TITLE
[230722] (토) 오늘의 공부

### ISSUE THREAD

**Issue by hoonii2** [let-s-study-with/TWL#147]
댓글로 자신이 어떤 공부 할지 체크박스를 만들고 얼만큼 했는지 체크해주세요.

**Comment by JeYeongR** [comment]
- [ ] 코테 스터디 문제 풀기
- [ ] 클린코드 2장 보기

**Comment by 724thomas** [comment]
알아서 일하는 진짜 인공지능 Auto-GPT 서비스 구현
- [ ] Chapter 1 Auto-GPT와 친해지기
- [ ] Chapter 2 Auto-GPT의 원리
- [ ] Chapter 3 Auto-GPT 맛보기
