### ISSUE TITLE
[230606] (화) 오늘의 공부

### ISSUE THREAD

**Issue by HongGuma-study** [let-s-study-with/TWL#15]
댓글로 자신이 어떤 공부 할지 체크박스를 만들고 얼만큼 했는지 체크해주세요.

**Comment by 724thomas** [comment]
- [ ] Graph 문제 5개 선택하여 풀기
- [ ] CS 스터디 멤버들 노트 정독

**Comment by JeYeongR** [comment]
- [ ] 프로그래머스 코딩 기초 트레이닝 Day 21 풀기
- [ ] 프로그래머스 코딩테스트 입문 Day 21 풀기
- [ ] "실전! 스프링 부트와 JPA 활용2" 강의 - 섹션 4 보기
---
시간남으면 
- [ ] "실전! 스프링 부트와 JPA 활용2" 강의 - 섹션 5 보기
- [ ] "실전! 스프링 부트와 JPA 활용2" 강의 - 섹션 6 보기

**Comment by flimberkim** [comment]
- [ ] 코테 준비(알고리즘 공부 + 문제풀이)
