### ISSUE TITLE
[230607] (수) 오늘의 공부

### ISSUE THREAD

**Issue by HongGuma-study** [let-s-study-with/TWL#16]
댓글로 자신이 어떤 공부 할지 체크박스를 만들고 얼만큼 했는지 체크해주세요.

**Comment by hoonii2** [comment]
- [ ] cka rbac 인증 정리
- [ ] cka workloads & scheduling 공부

**Comment by JeYeongR** [comment]
- [ ] 프로그래머스 코딩 기초 트레이닝 Day 22 풀기
- [ ] 프로그래머스 코딩테스트 입문 Day 22 풀기
- [ ] "실전! 스프링 부트와 JPA 활용2" 강의 - 섹션 5 보기
- [ ] "실전! 스프링 부트와 JPA 활용2" 강의 - 섹션 6 보기

**Comment by lala9663** [comment]
- [ ] JPA 활용 1 마무리
- [ ] 프로그래머스 1단계 2문제 풀기
- [ ] 이번 주 할 내용 정리하기
- [ ] 온 보딩 사전과제?

**Comment by smallsnail-study** [comment]
- [ ] 코테 강의 Ch 03.배열 수강
- [ ] 19:30~22:30 원티드프리온보딩 강의
---------------------------------------------
시간 남으면
- [ ] 정처기 소프트웨어 개발방법론 선정 문제풀이&정리

**Comment by suji5262** [comment]
- [ ] AWS 강의듣기
- [ ] 정처기 공부하기

**Comment by 724thomas** [comment]
- [ ] Graph 문제 풀기
- [ ] CS 노트 복습
- [ ] CS 스터디 노트 복습

**Comment by HongGuma-study** [comment]
습관 재활치료
- [ ] 연속된 숫자의 합
- [ ] 다음에 올 숫자
----
- [ ] 안전지대

**Comment by flimberkim** [comment]
- [ ] 백트래킹 문제 풀기
- [ ] 이분탐색 문제 풀기
