### ISSUE TITLE
[230802] (수) 오늘의 공부

### ISSUE THREAD

**Issue by hoonii2** [let-s-study-with/TWL#169]
댓글로 자신이 어떤 공부 할지 체크박스를 만들고 얼만큼 했는지 체크해주세요.

**Comment by JeYeongR** [comment]
- [ ] 코테 스터디 문제 풀기

**Comment by hoonii2** [comment]
- [ ] elk monitoring
- [ ] Calico CNI 동작 원리 정리
- [ ] 코테 스터디 문제 풀기
- [ ] 영단어

**Comment by suji5262** [comment]
- [ ] JPA 공부
- [ ] CS 공부
