### ISSUE TITLE
[230807] (월) 오늘의 공부

### ISSUE THREAD

**Issue by hoonii2** [let-s-study-with/TWL#177]
댓글로 자신이 어떤 공부 할지 체크박스를 만들고 얼만큼 했는지 체크해주세요.

**Comment by smallsnail-study** [comment]
- [ ]  코테 스터디 2문제
- [ ]  SQLD 정규화 문제풀이&이론정리
- [ ]  스프링 섹션 6. 스프링 DB 접근 기술 수강&내용정리
- [ ]  게시판 프로젝트

**Comment by lala9663** [comment]
- [ ] CI/CD 
- [ ] 내용 정리
- [ ] 운동

**Comment by JeYeongR** [comment]
- [ ] 백준 문제 풀기

**Comment by hoonii2** [comment]
- [ ] 코테 스터디 문제 풀기
- [ ] 영단어 & 국사..
