### ISSUE TITLE
[230922](금) 오늘의 공부

### ISSUE THREAD

**Issue by suji5262** [let-s-study-with/TWL#234]
댓글로 자신이 어떤 공부 할지 체크박스를 만들고 얼만큼 했는지 체크해주세요.

**Comment by lala9663** [comment]
- [ ] 옵시디언 적용하기
- [ ] TIL 옵시디언으로 변경하기
- [ ] 이펙티브 자바 아이템 11 12 정리
- [ ] 프로젝트
- [ ] 운동
