### ISSUE TITLE
[230927] (수) 오늘의 공부

### ISSUE THREAD

**Issue by suji5262** [let-s-study-with/TWL#239]
댓글로 자신이 어떤 공부 할지 체크박스를 만들고 얼만큼 했는지 체크해주세요.

**Comment by 724thomas** [comment]
- [ ] Dave 파일 찾기 & csapp 참고해서 CS스터디 (운영체제) 작성
- [ ] 패캠 인터뷰 협의
- [ ] 펫누리 백로그 작성....음.............
- [ ] 이분탐색, 슬라이딩 윈도우 문제 풀기 나머지 풀기

**Comment by suji5262** [comment]
- [ ] 정처기 실기
- [ ] JPA 공부
