### ISSUE TITLE
[231001] (일) 오늘의 공부

### ISSUE THREAD

**Issue by suji5262** [let-s-study-with/TWL#243]
댓글로 자신이 어떤 공부 할지 체크박스를 만들고 얼만큼 했는지 체크해주세요.

**Comment by 724thomas** [comment]
- [ ] 운영체제p1 면접 질문, 면접 준비
- [ ] 운영체제p2 정리
- [ ] csapp - 컴퓨터 시스템으로의 여행 (1.1~1.10)
- [ ] 코테 문제 풀기
- [ ] 모니터와 동기화 - 백발백중
- [ ] 주메모리의 관리 - 운체
- [ ] 페이징과 스와핑 - 운체
- [ ] 페이지 교체 알고리즘 - 운체
- [ ] 파일과 디렉터리 - 운체
- [ ] 파일 시스템 - 컴공 기초
