### ISSUE TITLE
[230614] (수) 오늘의 공부

### ISSUE THREAD

**Issue by HongGuma-study** [let-s-study-with/TWL#48]
댓글로 자신이 어떤 공부 할지 체크박스를 만들고 얼만큼 했는지 체크해주세요.

**Comment by hoonii2** [comment]
- [ ] cka 패캠 문제 풀기
- [ ] cka kodekloud test

**Comment by smallsnail-study** [comment]
- [ ]  [10158] 개미 다시풀기
- [ ]  [1236] 성 지키기 다시풀기
- [ ]  [10431] 줄세우기 다시풀기
- [ ]  [10989] 수 정렬하기 3 다시풀기
- [ ]  [3273] 두 수의 합 다시풀기

---

시간 남으면

- [ ]  정처기 서버프로그램 구현 문제&이론정리
- [ ]  정처기 소프트웨어 개발방법론활용 문제&이론정리

**Comment by suji5262** [comment]
- [ ] 정처기 공부 + 운영체제 강의듣기
- [ ] AWS 강의듣기
---
- [ ] 코데 강의듣기

**Comment by HongGuma-study** [comment]
- [ ] voca day 1
- [ ] reading 1주차 2
- [ ] 문자열 밀기
- [ ] 저주의 숫자3
- [ ] 대소문자 바꿔서 출력하기
- [ ] 유한소수 판별하기
- [ ] 무작위로 k개 뽑기

**Comment by JeYeongR** [comment]
- [ ] "스프링 핵심 원리 - 고급편" 강의 - 섹션 1 보기
